### PR TITLE
If deleting a resource gives a 404 we should be fine

### PR DESCRIPTION
**Pull request by juandspy**
Fix some errors appearing in all the tests, f.e in [this one](https://github.com/redhat-developer/terraform-provider-rhoas/actions/runs/3338302597/jobs/5525793507#step:10:77):
```
Error: Error waiting for example instance (FztVctEr3pp1_zWNGjG-M) to be deleted: The requested resource or service could not be found :: 404 Not Found :: mock-api:8000/api/kafkas_mgmt/v1/kafkas/FztVctEr3pp1_zWNGjG-M :: GET
```

Tests are still not passing probably because of the mock server.

### CODE REVIEW

**Comment by jackdelahunt** [comment]
LGTM 👍  just need to fix linter

**Review by jackdelahunt — APPROVED** [review]
LGTM 👍 just need to fix linter

**Comment by juandspy** [comment]
> LGTM +1 just need to fix linter

last version of golang ci lint should be fixed: [see](https://github.com/golangci/golangci-lint-action/pull/578). Not sure why in this CI it's not working :/

**Comment by juandspy** [comment]
> LGTM +1 just need to fix linter

fixed, I had to find a workaround

**Pull request merged**
