### PR TITLE
Kafka datasources and service account refactor

### PR DESCRIPTION
**Pull request by jackdelahunt**
## Verify
- Use the folllowing terraform config
```
terraform {
  required_providers {
    rhoas = {
      source  = "registry.terraform.io/redhat-developer/rhoas"
      version = "0.1.0"
    }
  }
}

provider "rhoas" {
    offline_token = "..."
}

resource "rhoas_kafka" "instance" {
    name = "instance"
}

resource "rhoas_service_account" "srvcaccnt" {
    name = "my-service-account"
}

data "rhoas_kafka" "datasource" {
    id = rhoas_kafka.instance.id
}
```
- `make install`
- `terraform init`
- `terraform apply`
- You should have a new kafka instance
- You should have a new service account
- The read from the kafka data source should work
- Change fields and run `terraform apply` again to update the kafka and service account

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
Encountered this issue trying to run `terraform apply`:
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

rhoas_service_account.srvcaccnt: Creating...
rhoas_kafka.instance: Creating...
╷
│ Error: Request cancelled
│ 
│   with rhoas_kafka.instance,
│   on main.tf line 14, in resource "rhoas_kafka" "instance":
│   14: resource "rhoas_kafka" "instance" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│   with rhoas_service_account.srvcaccnt,
│   on main.tf line 18, in resource "rhoas_service_account" "srvcaccnt":
│   18: resource "rhoas_service_account" "srvcaccnt" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-rhoas plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xb13bf1]

goroutine 66 [running]:
redhat.com/rhoas/rhoas-terraform-provider/m/rhoas/serviceaccounts.serviceAccountCreate({0xdc3060, 0xc00007fe60}, 0x0?, {0xb61660?, 0xc000114980?})
        /home/rkpattnaik780/coding/redhat/mk/terraform-provider-rhoas/rhoas/serviceaccounts/resource_serviceaccount.go:143 +0x5d1
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001267e0, {0xdc3098, 0xc0000cf1d0}, 0xd?, {0xb61660, 0xc000114980})
        /home/rkpattnaik780/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001267e0, {0xdc3098, 0xc0000cf1d0}, 0xc0004b7ba0, 0xc00028f780, {0xb61660, 0xc000114980})
        /home/rkpattnaik780/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001138f0, {0xdc3098?, 0xc00068aa20?}, 0xc00068c2d0)
        /home/rkpattnaik780/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.21.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003f4d20, {0xdc3098?, 0xc00068a1e0?}, 0xc000366150)
        /home/rkpattnaik780/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc63600?, 0xc0003f4d20}, {0xdc3098, 0xc00068a1e0}, 0xc0003660e0, 0x0)
        /home/rkpattnaik780/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000436000, {0xdc5b48, 0xc00048a1a0}, 0xc000694000, 0xc000427c20, 0x1298ec0, 0x0)
        /home/rkpattnaik780/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1295 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc000436000, {0xdc5b48, 0xc00048a1a0}, 0xc000694000, 0x0)
        /home/rkpattnaik780/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:1636 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/rkpattnaik780/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/rkpattnaik780/go/pkg/mod/google.golang.org/grpc@v1.48.0/server.go:930 +0x28a

Error: The terraform-provider-rhoas plugin crashed!
```

**Comment by jackdelahunt** [comment]
@rkpattnaik780 retry the problem you were getting was from and error occurring and then us failing to handle it properly. So you should get a new error but not panic.

**Comment by rkpattnaik780** [comment]
I confirm I don't see a panic now for the last issue, just error. Was getting the following error while trying to do a `terraform init`. Getting rid of the temp files created got it working fine.

```
Initializing the backend...

Initializing provider plugins...
- Reusing previous version of redhat-developer/rhoas from the dependency lock file
- Installing redhat-developer/rhoas v0.1.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing redhat-developer/rhoas v0.1.0: the local package for registry.terraform.io/redhat-developer/rhoas 0.1.0 doesn't match any of the checksums previously recorded
│ in the dependency lock file (this might be because the available checksums are for packages targeting different platforms); for more information:
│ https://www.terraform.io/language/provider-checksum-verification
```

**Comment by jackdelahunt** [comment]
@rkpattnaik780 

So this errror comes from terraform itself and it is due to you running make install multiple times. Terraform assumes the same binary will be used so when you change it, it is not happy. 

Delete in the project folder:
- `.terraform.lock.hcl`
- `terraform.tf.state`
- `terraform.tf.state.backup`

**Review by rkpattnaik780 — APPROVED** [review]

**Pull request merged**
